name: MatthewErickson
favicon: null
layout_spectrum: 0.77227
typography_spectrum: 0.73577
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#09364c'
    - '#31c1e9'
    - '#0280d0'
    - '#ffffff'
    - '#ff6ba5'
  brandStrength: 0.25
  lightness: 0
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
