name: MatthewErickson
favicon: null
layout_spectrum: 0.5411060156766325
typography_spectrum: 0.44264214811846614
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.273192705353722
  lightness: 0.9068603322375566
  saturation: 0.8565478429663926
  rhythmicContrast: 0.7509829213377088
purpose: []
